name: Python Tests  

on:  
  push:  
    branches: [dev, feature/*]  
  pull_request:  
    branches: [main]  

jobs:  
  test:  
    runs-on: ubuntu-latest  
    steps:  
    - uses: actions/checkout@v4  
    - name: Set up Python  
      uses: actions/setup-python@v4  
      with:  
        python-version: '3.x'  
    - name: Install dependencies  
      run: pip install -r requirements.txt  
    - name: Run tests  
      run: pytest tests/  # Add your test command here  